project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Decision Tree Alternate Visualization"
  author:
    - Addeson Lehv (al4246)
  repo-url: https://github.com/addesonlehv/decision_tree_alt_viz
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - methods.qmd
    - results.qmd
    - improvements.qmd
    - conclusion.qmd

format:
  html:
    theme: yeti
    code-fold: true


